rails/config/routes.rb
Vogon::Application.routes.draw do
  
  match "/beta" => "home#buscar"
  root :to => "home#buscar"
  
  match "alertas/alerta/:prod_id/:prod_price" =>  "alertas#alerta"
  
  resources :authorizations
  match "/auth/:provider/callback" => "authorizations#create"
  match "/auth/failure" => "authorizations#failure"
  match "/signout" => "sessions#destroy", :as => :signout
  
  match 'home/buscar', :controller => 'home', :action => 'buscar'
  
  resources :alertas
  
  resources :produtos

  resources :users

  
end

rails/app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :user_id, :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash, user = nil)
    user ||= User.create_from_hash!(hash)
    Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  end
  
end

rails/app/controllers/authorizations_controller.rb
# encoding: utf-8
class AuthorizationsController < ApplicationController

  def index
    @authorizations = current_user.authorizations if current_user
    @user = current_user if current_user #para editar tambem dados do user
  end
    
  def create
    logger.debug "##############" + request.env["omniauth.auth"].to_yaml + "##############"
    omniauth = request.env["omniauth.auth"]
    @auth = Authorization.find_from_hash(omniauth)
    if @auth
      flash[:notice] = "Logou com sucesso."
      session[:user_id] = @auth.user.id
      #redirect_to root_path and return #TODO
      redirect_to "/beta" and return #temporariamente no beta
    elsif current_user
      @auth = Authorization.create_from_hash(omniauth, current_user)
      flash[:notice] = "Login adicionado."
      current_user.authorizations.find_or_create_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    else
      @auth = Authorization.create_from_hash(omniauth, current_user)
      session[:user_id] = @auth.user.id
      flash[:notice] = "Seu cadastro foi criado com sucesso."
    end
    redirect_to authorizations_url
  end

  def destroy
    @authorization = current_user.authorizations.find(params[:id])
    @authorization.destroy
    flash[:notice] = "Login deletado com sucesso."
    redirect_to authorizations_url
  end

  def failure
    flash[:notice] = "Ocorreu um erro no acesso ou desautorizado, tente novamente por favor."
    redirect_to authorizations_url
  end
end

rails/app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

rails/app/views/authorizations/_login.html.erb
 <% if current_user %>
   <p>Olá <%= current_user.name %><p>
       <p>
         você está conectado com:

    <% @providers = [] %>
    <% current_user.authorizations.each do |a| %>
      <% @providers.push  a.provider %>
    <% end %>
  
  <% %w(twitter facebook google open_id yahoo).each do |provider| %>
    <% if @providers.include? provider %>
      <%= image_tag "#{provider}_32.png", :size => "32x32", :alt => provider %>
    <% end %>
  <% end %>
       </p>
  <p>Conecte também com:
  <% %w(twitter facebook google open_id yahoo).each do |provider| %>
    <% unless @providers.include? provider %>
      <%= link_to "", "/auth/#{provider}", :class => "#{provider}_login", :alt => "Logar com #{provider}" %>
    <% end %>
  <% end %>
  <p>
  <p>
    <%= link_to "Editar cadastro", authorizations_path %>
    <%= link_to "Sair", signout_path %>
  </p>
<% else %>
  Conecte com: &nbsp;
  <%= link_to "", "/auth/twitter", :class => "twitter_login" , :alt => "Logar com Twitter"%>
  <%= link_to "", "/auth/facebook", :class => "facebook_login", :alt => "Logar com Facebook" %>
  <%= link_to "", "/auth/google", :class => "google_login", :alt => "Logar com Google" %>
  <%= link_to "", "/auth/open_id", :class => "open_id_login", :alt => "Logar com OpenID" %>
  <%= link_to "", "/auth/yahoo", :class => "yahoo_login", :alt => "Logar com Yahoo" %>
<% end %>

rails/app/views/authorizations/index.html.erb
<% title "Autorização" %>

<% if @authorizations %>
  <% unless @authorizations.empty? %>
    <p><strong>Seus serviços cadastrados:</strong></p>
    <div class="authorizations">
      <% for authorization in @authorizations %>
        <div class="authorization">
          <%= image_tag "#{authorization.provider}_32.png", :size => "32x32" %>
          <div class="provider"><%= authorization.provider.titleize %></div>
          <div class="uid"><%= authorization.uid %></div>
          <%= link_to "X", authorization, :confirm => 'Tem certeza que deseja remover esta autorização?', :method => :delete, :class => "remove" %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Adicione outro serviço de autenticação:</strong></p>
<% else %>
  <p><strong>Serviços de autenticação disponíveis:</strong></p>
<% end %>

<a href="/auth/twitter" class="auth_provider">
  <%= image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" %>
  Twitter
</a>
<a href="/auth/facebook" class="auth_provider">
  <%= image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" %>
  Facebook
</a>
<a href="/auth/google" class="auth_provider">
  <%= image_tag "google_64.png", :size => "64x64", :alt => "Google" %>
  Google
</a>
<a href="/auth/open_id" class="auth_provider">
  <%= image_tag "open_id_64.png", :size => "64x64", :alt => "OpenID" %>
  OpenID
</a>
<a href="/auth/yahoo" class="auth_provider">
  <%= image_tag "yahoo_64.png", :size => "64x64", :alt => "Yahoo" %>
  Yahoo
</a>
<div class="clear"></div>
  <% if @user %>
  <p><strong>Edite seus dados:</strong></p>
  <%= render "users/form" %>
  <% end %>